variable "tfe_token" {}

variable "oauth_token_id" {} # this is token id from TFC /settings/vcs provioder - generated by TFC, after regenerate client secret on GitHub regennerate token id

variable "hcp_client_secret" {}

variable "hcp_client_id" {}

variable "tfe_aws_role" {}